# Chapter - 1
## Getting and Knowing your Data

In [17]:
import pandas as pd

In [18]:
pd.read_csv(filepath_or_buffer = "data.tsv.txt", sep = "\t") # this is the method to open tab seperated values in read_csv function

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [19]:
pd.read_table(filepath_or_buffer = "output_with_timeline.csv", sep = ",") # this is the method to open comma seperated values in read_table function

,Start_Time,End_Time,PROGRAM/AD/SONGS,TIMELINE
0,05:00:00,05:01:11,NO AUDIO PLAYED,05:00:00-05:01:11
1,05:01:11,05:02:05,JINGLE: RADIO CITY 91.1 FM SONG,05:01:11-05:02:05
2,05:02:05,05:02:11,JINGLE: SRI VENKATESHWARA SUPRABHATHAM SONG INTRO,05:02:05-05:02:11
3,05:02:11,05:22:43,"SONG: SRI VENKATESHWARA SUPRABATHAM, MS SUBBUL...",05:02:11-05:22:43
4,05:22:43,05:23:54,"PROGRAM: AALAYA DHARISANAM, RJ SHAKTHI",05:22:43-05:23:54
...,...,...,...,...
1372,23:53:46,23:54:05,JINGLE: RADIO CITY,23:53:46-23:54:05
1373,23:54:05,23:54:33,JINGLE: DESAANDHIRI SONG INTRO,23:54:05-23:54:33
1374,23:54:33,23:57:42,"SONG: DESAANDHIRI, SIDDHARTH & SANTHOSH NARAYA...",23:54:33-23:57:42
1375,23:57:42,23:58:00,JINGLE: RADIO CITY,23:57:42-23:58:00
1376,23:58:00,23:59:59,"SONG: PATTUKUTTY, YUVAN SHANKAR RAJA, RAJA RAN...",23:58:00-23:59:59

In [20]:
order_details = pd.read_table(filepath_or_buffer = "data.tsv.txt")
order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

## Perform Initial Analysis

In [21]:
# Function contains --> ()
# Attribute doesn't contains  --> ()

In [22]:
order_details.shape

(4622, 5)

## Terminology Alert
* Rows - Observations/Record
* Column - Features/Parameters

In [23]:
order_details.isnull()

      order_id  quantity  item_name  choice_description  item_price
0        False     False      False                True       False
1        False     False      False               False       False
2        False     False      False               False       False
3        False     False      False                True       False
4        False     False      False               False       False
...        ...       ...        ...                 ...         ...
4617     False     False      False               False       False
4618     False     False      False               False       False
4619     False     False      False               False       False
4620     False     False      False               False       False
4621     False     False      False               False       False

[4622 rows x 5 columns]

In [24]:
order_details.isnull().sum() # Chain of Functions or Chain of Commands

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [25]:
order_details.describe()

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

In [26]:
order_details.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

In [27]:
order_details.describe(include = 'all')

           order_id     quantity     item_name choice_description item_price
count   4622.000000  4622.000000          4622               3376       4622
unique          NaN          NaN            50               1043         78
top             NaN          NaN  Chicken Bowl        [Diet Coke]     $8.75
freq            NaN          NaN           726                134        730
mean     927.254868     1.075725           NaN                NaN        NaN
std      528.890796     0.410186           NaN                NaN        NaN
min        1.000000     1.000000           NaN                NaN        NaN
25%      477.250000     1.000000           NaN                NaN        NaN
50%      926.000000     1.000000           NaN                NaN        NaN
75%     1393.000000     1.000000           NaN                NaN        NaN
max     1834.000000    15.000000           NaN                NaN        NaN

## Find out the items sold in the Restaurent

In [28]:
order_details.nunique()

order_id              1834
quantity                 9
item_name               50
choice_description    1043
item_price              78
dtype: int64

In [29]:
print(order_details["item_name"].unique())

['Chips and Fresh Tomato Salsa' 'Izze' 'Nantucket Nectar'
 'Chips and Tomatillo-Green Chili Salsa' 'Chicken Bowl' 'Side of Chips'
 'Steak Burrito' 'Steak Soft Tacos' 'Chips and Guacamole'
 'Chicken Crispy Tacos' 'Chicken Soft Tacos' 'Chicken Burrito'
 'Canned Soda' 'Barbacoa Burrito' 'Carnitas Burrito' 'Carnitas Bowl'
 'Bottled Water' 'Chips and Tomatillo Green Chili Salsa' 'Barbacoa Bowl'
 'Chips' 'Chicken Salad Bowl' 'Steak Bowl' 'Barbacoa Soft Tacos'
 'Veggie Burrito' 'Veggie Bowl' 'Steak Crispy Tacos'
 'Chips and Tomatillo Red Chili Salsa' 'Barbacoa Crispy Tacos'
 'Veggie Salad Bowl' 'Chips and Roasted Chili-Corn Salsa'
 'Chips and Roasted Chili Corn Salsa' 'Carnitas Soft Tacos'
 'Chicken Salad' 'Canned Soft Drink' 'Steak Salad Bowl'
 '6 Pack Soft Drink' 'Chips and Tomatillo-Red Chili Salsa' 'Bowl'
 'Burrito' 'Crispy Tacos' 'Carnitas Crispy Tacos' 'Steak Salad'
 'Chips and Mild Fresh Tomato Salsa' 'Veggie Soft Tacos'
 'Carnitas Salad Bowl' 'Barbacoa Salad Bowl' 'Salad' 'Veggie Crispy Tacos'
 'Veggie Salad' 'Carnitas Salad']

## Give me the list of Top Selling Items

In [30]:
order_details.groupby(by = "item_name")["quantity"].sum().sort_values() # syntax for Ascending order

item_name
Carnitas Salad                             1
Chips and Mild Fresh Tomato Salsa          1
Veggie Crispy Tacos                        1
Crispy Tacos                               2
Salad                                      2
Steak Salad                                4
Bowl                                       4
Burrito                                    6
Carnitas Salad Bowl                        6
Veggie Salad                               6
Veggie Soft Tacos                          8
Carnitas Crispy Tacos                      8
Chicken Salad                              9
Barbacoa Salad Bowl                       10
Barbacoa Crispy Tacos                     12
Chips and Roasted Chili-Corn Salsa        18
Veggie Salad Bowl                         18
Izze                                      20
Chips and Roasted Chili Corn Salsa        23
Barbacoa Soft Tacos                       25
Chips and Tomatillo-Red Chili Salsa       25
Nantucket Nectar                          29
Steak Salad Bowl                          31
Chips and Tomatillo-Green Chili Salsa     33
Steak Crispy Tacos                        36
Carnitas Soft Tacos                       40
Chips and Tomatillo Green Chili Salsa     45
Chicken Crispy Tacos                      50
Chips and Tomatillo Red Chili Salsa       50
6 Pack Soft Drink                         55
Steak Soft Tacos                          56
Carnitas Burrito                          60
Barbacoa Bowl                             66
Carnitas Bowl                             71
Veggie Bowl                               87
Barbacoa Burrito                          91
Veggie Burrito                            97
Side of Chips                            110
Chicken Soft Tacos                       120
Chicken Salad Bowl                       123
Canned Soda                              126
Chips and Fresh Tomato Salsa             130
Bottled Water                            211
Steak Bowl                               221
Chips                                    230
Canned Soft Drink                        351
Steak Burrito                            386
Chips and Guacamole                      506
Chicken Burrito                          591
Chicken Bowl                             761
Name: quantity, dtype: int64

In [31]:
order_details.groupby(by = "item_name")["quantity"].sum().sort_values(ascending = False) # syntax for Descending order

item_name
Chicken Bowl                             761
Chicken Burrito                          591
Chips and Guacamole                      506
Steak Burrito                            386
Canned Soft Drink                        351
Chips                                    230
Steak Bowl                               221
Bottled Water                            211
Chips and Fresh Tomato Salsa             130
Canned Soda                              126
Chicken Salad Bowl                       123
Chicken Soft Tacos                       120
Side of Chips                            110
Veggie Burrito                            97
Barbacoa Burrito                          91
Veggie Bowl                               87
Carnitas Bowl                             71
Barbacoa Bowl                             66
Carnitas Burrito                          60
Steak Soft Tacos                          56
6 Pack Soft Drink                         55
Chicken Crispy Tacos                      50
Chips and Tomatillo Red Chili Salsa       50
Chips and Tomatillo Green Chili Salsa     45
Carnitas Soft Tacos                       40
Steak Crispy Tacos                        36
Chips and Tomatillo-Green Chili Salsa     33
Steak Salad Bowl                          31
Nantucket Nectar                          29
Chips and Tomatillo-Red Chili Salsa       25
Barbacoa Soft Tacos                       25
Chips and Roasted Chili Corn Salsa        23
Izze                                      20
Veggie Salad Bowl                         18
Chips and Roasted Chili-Corn Salsa        18
Barbacoa Crispy Tacos                     12
Barbacoa Salad Bowl                       10
Chicken Salad                              9
Carnitas Crispy Tacos                      8
Veggie Soft Tacos                          8
Burrito                                    6
Carnitas Salad Bowl                        6
Veggie Salad                               6
Bowl                                       4
Steak Salad                                4
Salad                                      2
Crispy Tacos                               2
Carnitas Salad                             1
Chips and Mild Fresh Tomato Salsa          1
Veggie Crispy Tacos                        1
Name: quantity, dtype: int64

In [32]:
order_details.groupby(by = "item_name")["quantity"].sum().sort_values(ascending = False).head()

item_name
Chicken Bowl           761
Chicken Burrito        591
Chips and Guacamole    506
Steak Burrito          386
Canned Soft Drink      351
Name: quantity, dtype: int64

In [33]:
order_details.groupby(by = "item_name")["quantity"].sum().sort_values(ascending = False).head(10)

item_name
Chicken Bowl                    761
Chicken Burrito                 591
Chips and Guacamole             506
Steak Burrito                   386
Canned Soft Drink               351
Chips                           230
Steak Bowl                      221
Bottled Water                   211
Chips and Fresh Tomato Salsa    130
Canned Soda                     126
Name: quantity, dtype: int64

## Give me the list of Least Selling Items

In [34]:
order_details.groupby(by = "item_name")["quantity"].sum()

item_name
6 Pack Soft Drink                         55
Barbacoa Bowl                             66
Barbacoa Burrito                          91
Barbacoa Crispy Tacos                     12
Barbacoa Salad Bowl                       10
Barbacoa Soft Tacos                       25
Bottled Water                            211
Bowl                                       4
Burrito                                    6
Canned Soda                              126
Canned Soft Drink                        351
Carnitas Bowl                             71
Carnitas Burrito                          60
Carnitas Crispy Tacos                      8
Carnitas Salad                             1
Carnitas Salad Bowl                        6
Carnitas Soft Tacos                       40
Chicken Bowl                             761
Chicken Burrito                          591
Chicken Crispy Tacos                      50
Chicken Salad                              9
Chicken Salad Bowl                       123
Chicken Soft Tacos                       120
Chips                                    230
Chips and Fresh Tomato Salsa             130
Chips and Guacamole                      506
Chips and Mild Fresh Tomato Salsa          1
Chips and Roasted Chili Corn Salsa        23
Chips and Roasted Chili-Corn Salsa        18
Chips and Tomatillo Green Chili Salsa     45
Chips and Tomatillo Red Chili Salsa       50
Chips and Tomatillo-Green Chili Salsa     33
Chips and Tomatillo-Red Chili Salsa       25
Crispy Tacos                               2
Izze                                      20
Nantucket Nectar                          29
Salad                                      2
Side of Chips                            110
Steak Bowl                               221
Steak Burrito                            386
Steak Crispy Tacos                        36
Steak Salad                                4
Steak Salad Bowl                          31
Steak Soft Tacos                          56
Veggie Bowl                               87
Veggie Burrito                            97
Veggie Crispy Tacos                        1
Veggie Salad                               6
Veggie Salad Bowl                         18
Veggie Soft Tacos                          8
Name: quantity, dtype: int64

In [35]:
order_details.groupby(by = "item_name")["quantity"].sum().sort_values() # syntax for Ascending order

item_name
Carnitas Salad                             1
Chips and Mild Fresh Tomato Salsa          1
Veggie Crispy Tacos                        1
Crispy Tacos                               2
Salad                                      2
Steak Salad                                4
Bowl                                       4
Burrito                                    6
Carnitas Salad Bowl                        6
Veggie Salad                               6
Veggie Soft Tacos                          8
Carnitas Crispy Tacos                      8
Chicken Salad                              9
Barbacoa Salad Bowl                       10
Barbacoa Crispy Tacos                     12
Chips and Roasted Chili-Corn Salsa        18
Veggie Salad Bowl                         18
Izze                                      20
Chips and Roasted Chili Corn Salsa        23
Barbacoa Soft Tacos                       25
Chips and Tomatillo-Red Chili Salsa       25
Nantucket Nectar                          29
Steak Salad Bowl                          31
Chips and Tomatillo-Green Chili Salsa     33
Steak Crispy Tacos                        36
Carnitas Soft Tacos                       40
Chips and Tomatillo Green Chili Salsa     45
Chicken Crispy Tacos                      50
Chips and Tomatillo Red Chili Salsa       50
6 Pack Soft Drink                         55
Steak Soft Tacos                          56
Carnitas Burrito                          60
Barbacoa Bowl                             66
Carnitas Bowl                             71
Veggie Bowl                               87
Barbacoa Burrito                          91
Veggie Burrito                            97
Side of Chips                            110
Chicken Soft Tacos                       120
Chicken Salad Bowl                       123
Canned Soda                              126
Chips and Fresh Tomato Salsa             130
Bottled Water                            211
Steak Bowl                               221
Chips                                    230
Canned Soft Drink                        351
Steak Burrito                            386
Chips and Guacamole                      506
Chicken Burrito                          591
Chicken Bowl                             761
Name: quantity, dtype: int64

In [36]:
order_details.groupby(by = "item_name")["quantity"].sum().sort_values().head()

item_name
Carnitas Salad                       1
Chips and Mild Fresh Tomato Salsa    1
Veggie Crispy Tacos                  1
Crispy Tacos                         2
Salad                                2
Name: quantity, dtype: int64

In [37]:
order_details.groupby(by = "item_name")["quantity"].sum().sort_values().head(9)

item_name
Carnitas Salad                       1
Chips and Mild Fresh Tomato Salsa    1
Veggie Crispy Tacos                  1
Crispy Tacos                         2
Salad                                2
Steak Salad                          4
Bowl                                 4
Burrito                              6
Carnitas Salad Bowl                  6
Name: quantity, dtype: int64

# Chapter - 2
## Data Cleaning:
1) Business Understanding
2) Data Collection
3) Data Understanding
4) Data Preparation

In [38]:
order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [39]:
order_details.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

In [40]:
order_details["item_price"].str.replace("$","")

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
         ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: object

In [41]:
order_details["item_price"].str.replace("$","").astype(float)

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: float64

In [42]:
order_details["item_price"] = order_details["item_price"].str.replace("$","").astype(float)

In [43]:
order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [44]:
order_details.dtypes

order_id                int64
quantity                int64
item_name              object
choice_description     object
item_price            float64
dtype: object

In [45]:
order_details.describe()

          order_id     quantity   item_price
count  4622.000000  4622.000000  4622.000000
mean    927.254868     1.075725     7.464336
std     528.890796     0.410186     4.245557
min       1.000000     1.000000     1.090000
25%     477.250000     1.000000     3.390000
50%     926.000000     1.000000     8.750000
75%    1393.000000     1.000000     9.250000
max    1834.000000    15.000000    44.250000

# Task

## Top 5 selling items individual revenue it made

In [46]:
order_details.groupby(["item_name","item_price"])["quantity"].sum().sort_values(ascending=False).head()

item_name            item_price
Chips and Guacamole  4.45          349
Chicken Bowl         8.75          313
Canned Soft Drink    1.25          264
Chicken Burrito      8.75          230
Chicken Bowl         11.25         228
Name: quantity, dtype: int64

In [47]:
 order_details["revenue"] = order_details["item_price"] * order_details["quantity"]

In [48]:
order_details.groupby("item_name")["revenue"].sum().sort_values(ascending=False).head(5)

item_name
Chicken Bowl           8044.63
Chicken Burrito        6387.06
Steak Burrito          4236.13
Steak Bowl             2479.81
Chips and Guacamole    2475.62
Name: revenue, dtype: float64

In [49]:
order_details["revenue"] = order_details["item_price"] * order_details["quantity"]
order_details["revenue"].sort_values(ascending = False).head()

3598    663.75
4152    150.00
1254    140.00
3602    140.00
3887    108.16
Name: revenue, dtype: float64

In [50]:
top5 = order_details.groupby(by = "item_name")["revenue"].sum().sort_values(ascending=False).head(5)
top5.sum()

np.float64(23623.25)

In [51]:
order_details["order_by_individual"] = order_details["order_id"] * order_details["quantity"]

In [52]:
order_details.groupby("order_id")["quantity"].sum()

order_id
1       4
2       2
3       2
4       2
5       2
       ..
1830    2
1831    3
1832    2
1833    2
1834    3
Name: quantity, Length: 1834, dtype: int64

In [53]:
order_details.groupby("order_id")["quantity"].sum().sort_values(ascending=False).head()

order_id
1443    35
926     23
1786    20
1660    19
759     18
Name: quantity, dtype: int64

In [54]:
order_details.groupby("order_id")["quantity"].sum().mode()

0    2
Name: quantity, dtype: int64

# Chapter - 3
## Pandas Data Structures
- 1D - Series
- 2D - Data Frame

In [78]:
pd.Series(data = [1,2,5.6,"$9.2"])

0       1
1       2
2     5.6
3    $9.2
dtype: object

In [79]:
pd.DataFrame(data = {
    "Name": ["Aakash", "Santhu", "Regwin", "Vignesh"],
    "Age": [23, 21, 24, 22],
    "Marks": [85, 90, 88, 92]
})

      Name  Age  Marks
0   Aakash   23     85
1   Santhu   21     90
2   Regwin   24     88
3  Vignesh   22     92

## Task - 2
- Create a meaningful Series
- Create a meaningful dataset using pandas DataFrame with Dict 5 observation across 6 features

In [80]:
pd.Series(
    data = [85, 78, 92, 88],
    index=["Maths", "Science", "English", "Computer"]
)

Maths       85
Science     78
English     92
Computer    88
dtype: int64

In [81]:
pd.DataFrame(data = {
    "Roll no":[101,102,103,104],
    "Name": ["Aakash", "Santhu", "Regwin", "Vignesh"],
    "Age": [23, 21, 24, 22],
    "Department":["CSE","EEE","ECE","MECH"],
    "Marks": [85, 90, 88, 92],
    "Grade":["A","A+","A","A+"]
})

   Roll no     Name  Age Department  Marks Grade
0      101   Aakash   23        CSE     85     A
1      102   Santhu   21        EEE     90    A+
2      103   Regwin   24        ECE     88     A
3      104  Vignesh   22       MECH     92    A+

# Chapter - 4
## Filtering & Selection & Sorting

In [82]:
euro_2012_data = pd.read_csv("Euro_2012_stats_TEAM.csv")

In [83]:
euro_2012_data

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

In [84]:
pd.set_option('display.max_columns',None) # to display all the columns in dataset. this step is not preffered.

In [85]:
euro_2012_data

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,Passes,Passes completed,Passing Accuracy,Touches,Crosses,Dribbles,Corners Taken,Tackles,Clearances,Interceptions,Clearances off line,Clean Sheets,Blocks,Goals conceded,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,2,1076,828,76.9%,1706,60,42,14,49,83,56,NaN,0,10,3,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,0,1565,1223,78.1%,2358,46,68,21,62,98,37,2.0,1,10,6,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,3,1298,1082,83.3%,1873,43,32,16,40,61,59,0.0,1,10,5,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,3,1488,1200,80.6%,2440,58,60,16,86,106,72,1.0,2,29,3,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,0,2066,1803,87.2%,2909,55,76,28,71,76,58,0.0,1,7,5,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,2,2774,2427,87.4%,3761,101,60,35,91,73,69,0.0,1,11,6,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,0,1187,911,76.7%,2016,52,53,10,65,123,87,0.0,1,23,7,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,2,3016,2531,83.9%,4363,75,75,30,98,137,136,1.0,2,18,7,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,0,1556,1381,88.7%,2163,50,49,22,34,41,41,0.0,0,9,5,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,1,1059,852,80.4%,1724,55,39,14,67,87,62,0.0,0,8,3,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,2,1891,1461,77.2%,2958,91,64,41,78,92,86,0.0,2,11,4,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,1,851,606,71.2%,1433,43,18,8,45,78,43,1.0,0,23,9,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,1,1602,1345,83.9%,2278,40,40,21,65,74,58,0.0,0,8,3,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,2,4317,3820,88.4%,5585,69,106,44,122,102,79,0.0,5,8,1,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,1,1192,965,80.9%,1806,44,29,7,56,54,45,0.0,1,12,5,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,2,1276,1043,81.7%,1894,33,26,18,65,97,29,0.0,0,4,4,13,76.5%,48,31,4,5,0,9,9,18

In [86]:
filtered_euro_data = euro_2012_data[["Team","Goals","Red Cards","Yellow Cards"]]

In [87]:
filtered_euro_data

                   Team  Goals  Red Cards  Yellow Cards
0               Croatia      4          0             9
1        Czech Republic      4          0             7
2               Denmark      4          0             4
3               England      5          0             5
4                France      3          0             6
5               Germany     10          0             4
6                Greece      5          1             9
7                 Italy      6          0            16
8           Netherlands      2          0             5
9                Poland      2          1             7
10             Portugal      6          0            12
11  Republic of Ireland      1          1             6
12               Russia      5          0             6
13                Spain     12          0            11
14               Sweden      5          0             7
15              Ukraine      2          0             5

In [88]:
filtered_euro_data["Yellow Cards"]

0      9
1      7
2      4
3      5
4      6
5      4
6      9
7     16
8      5
9      7
10    12
11     6
12     6
13    11
14     7
15     5
Name: Yellow Cards, dtype: int64

In [89]:
filtered_euro_data.sort_values(by = "Yellow Cards",ascending = False)

                   Team  Goals  Red Cards  Yellow Cards
7                 Italy      6          0            16
10             Portugal      6          0            12
13                Spain     12          0            11
0               Croatia      4          0             9
6                Greece      5          1             9
14               Sweden      5          0             7
9                Poland      2          1             7
1        Czech Republic      4          0             7
12               Russia      5          0             6
11  Republic of Ireland      1          1             6
4                France      3          0             6
3               England      5          0             5
8           Netherlands      2          0             5
15              Ukraine      2          0             5
5               Germany     10          0             4
2               Denmark      4          0             4

## Top 5 Yellow Cards Team

In [90]:
filtered_euro_data.sort_values(by = "Yellow Cards",ascending = False).head()

        Team  Goals  Red Cards  Yellow Cards
7      Italy      6          0            16
10  Portugal      6          0            12
13     Spain     12          0            11
0    Croatia      4          0             9
6     Greece      5          1             9

## List the teams which has got Red Cards

In [91]:
filtered_euro_data["Red Cards"] == 1

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9      True
10    False
11     True
12    False
13    False
14    False
15    False
Name: Red Cards, dtype: bool

In [92]:
filtered_euro_data[filtered_euro_data["Red Cards"] == 1]

                   Team  Goals  Red Cards  Yellow Cards
6                Greece      5          1             9
9                Poland      2          1             7
11  Republic of Ireland      1          1             6

## List the teams which has got more than 8 Yellow Cards

In [93]:
filtered_euro_data[filtered_euro_data["Yellow Cards"] >= 8]

        Team  Goals  Red Cards  Yellow Cards
0    Croatia      4          0             9
6     Greece      5          1             9
7      Italy      6          0            16
10  Portugal      6          0            12
13     Spain     12          0            11

# Task - 3
1) Find Out 5 New Questions along with Script Answers

In [94]:
filtered_euro_data.groupby(by = "Team")["Goals"].sum().sort_values(ascending = False).head()

Team
Spain       12
Germany     10
Portugal     6
Italy        6
Sweden       5
Name: Goals, dtype: int64

In [95]:
filtered_euro_data[filtered_euro_data["Goals"] > 5]

        Team  Goals  Red Cards  Yellow Cards
5    Germany     10          0             4
7      Italy      6          0            16
10  Portugal      6          0            12
13     Spain     12          0            11

In [96]:
filtered_euro_data.sort_values(by = "Goals",ascending = False).head()

        Team  Goals  Red Cards  Yellow Cards
13     Spain     12          0            11
5    Germany     10          0             4
10  Portugal      6          0            12
7      Italy      6          0            16
14    Sweden      5          0             7

In [97]:
filtered_euro_data2 = euro_2012_data[["Team","Goals","Penalty goals","Penalties not scored"]]

In [98]:
filtered_euro_data2

                   Team  Goals  Penalty goals  Penalties not scored
0               Croatia      4              0                     0
1        Czech Republic      4              0                     0
2               Denmark      4              0                     0
3               England      5              0                     0
4                France      3              0                     0
5               Germany     10              1                     0
6                Greece      5              1                     1
7                 Italy      6              0                     0
8           Netherlands      2              0                     0
9                Poland      2              0                     0
10             Portugal      6              0                     0
11  Republic of Ireland      1              0                     0
12               Russia      5              0                     0
13                Spain     12              1                     0
14               Sweden      5              0                     0
15              Ukraine      2              0                     0

In [99]:
filtered_euro_data2.sort_values(by = "Penalty goals", ascending = False).head()

       Team  Goals  Penalty goals  Penalties not scored
6    Greece      5              1                     1
5   Germany     10              1                     0
13    Spain     12              1                     0
0   Croatia      4              0                     0
3   England      5              0                     0

In [100]:
filtered_euro_data3 = euro_2012_data[["Team","Goals","Shooting Accuracy","Passing Accuracy"]]

In [101]:
filtered_euro_data3

                   Team  Goals Shooting Accuracy Passing Accuracy
0               Croatia      4             51.9%            76.9%
1        Czech Republic      4             41.9%            78.1%
2               Denmark      4             50.0%            83.3%
3               England      5             50.0%            80.6%
4                France      3             37.9%            87.2%
5               Germany     10             47.8%            87.4%
6                Greece      5             30.7%            76.7%
7                 Italy      6             43.0%            83.9%
8           Netherlands      2             25.0%            88.7%
9                Poland      2             39.4%            80.4%
10             Portugal      6             34.3%            77.2%
11  Republic of Ireland      1             36.8%            71.2%
12               Russia      5             22.5%            83.9%
13                Spain     12             55.9%            88.4%
14               Sweden      5             47.2%            80.9%
15              Ukraine      2             21.2%            81.7%

In [102]:
filtered_euro_data3.sort_values(by="Shooting Accuracy", ascending=False).head()

       Team  Goals Shooting Accuracy Passing Accuracy
13    Spain     12             55.9%            88.4%
0   Croatia      4             51.9%            76.9%
2   Denmark      4             50.0%            83.3%
3   England      5             50.0%            80.6%
5   Germany     10             47.8%            87.4%

In [103]:
filtered_euro_data3 = euro_2012_data[["Team","Goals","Shooting Accuracy","Passing Accuracy"]].copy()

In [104]:
filtered_euro_data3["Passing Accuracy"] = filtered_euro_data3["Passing Accuracy"].str.replace("%","").astype(float)

In [105]:
filtered_euro_data3["Passing Accuracy"]

0     76.9
1     78.1
2     83.3
3     80.6
4     87.2
5     87.4
6     76.7
7     83.9
8     88.7
9     80.4
10    77.2
11    71.2
12    83.9
13    88.4
14    80.9
15    81.7
Name: Passing Accuracy, dtype: float64

In [106]:
filtered_euro_data3.sort_values(by="Passing Accuracy", ascending=False).head()

           Team  Goals Shooting Accuracy  Passing Accuracy
8   Netherlands      2             25.0%              88.7
13        Spain     12             55.9%              88.4
5       Germany     10             47.8%              87.4
4        France      3             37.9%              87.2
7         Italy      6             43.0%              83.9

# Chapter - 5
## How to Deal with Missing Values

In [107]:
proitbridge_emp_data = pd.read_csv("employee_data.csv")

In [108]:
proitbridge_emp_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech      NaN  12-11-2020

## Data Cleaning: Level 1

### Always Recomended: I'll call to my client and check with him if he can give the right data

#### Incase, client asking us to perform the data cleaning Operations

### Step 1: Remove Duplicate Entries/Records

In [109]:
proitbridge_emp_data.drop_duplicates(inplace = True) # The complete operations will impact the Original Dataset

In [110]:
proitbridge_emp_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022

In [111]:
proitbridge_emp_data.shape

(7, 5)

### Step 2: Find out Null Entries

In [112]:
proitbridge_emp_data.isnull()

    Name    Age  Department  Salary  Join_Date
0  False  False       False   False      False
1  False  False       False    True      False
2  False   True       False   False      False
3  False  False       False   False      False
4  False  False       False   False      False
5  False  False       False   False      False
6   True  False       False   False      False

In [113]:
proitbridge_emp_data.isnull().sum()

Name          1
Age           1
Department    0
Salary        1
Join_Date     0
dtype: int64

### Step 3: Drop the Null Entries

In [114]:
proitbridge_emp_data.dropna(inplace = True)

In [115]:
proitbridge_emp_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023

In [116]:
proitbridge_emp_data.shape

(4, 5)

### Step 4: Record in a Document
- Client Gave totally 7 observations out of which 3 entries are removed because those records do not have complete information.
### Step 5: Get Approval
- Send this to Client and get the approval to proceed for Model Building or Model Training.

In [117]:
proitbridge_emp_data.isnull().sum()

Name          0
Age           0
Department    0
Salary        0
Join_Date     0
dtype: int64

## Data Cleaning: Level 2

In [55]:
employee_details = pd.read_excel("employee_data_updated.xlsx", sheet_name = "Employee_Data_From_Image")

In [56]:
employee_details

             Name   Age Department   Salary   Join_Date
0          Rajesh  29.0        Ops  60000.0  21-05-2023
1           Nasir  31.0    IT Tech  62000.0  12-11-2020
2         Mathiew   NaN    Support  58000.0  15-01-2025
3         Gilbert  29.0        Ops  60000.0  21-05-2021
4           Kevin  28.0    Support  61000.0  30-07-2024
5           Navin  35.0    Support  72000.0  19-08-2023
6             NaN  40.0    IT Tech  64000.0  10-09-2022
7          Roshan  31.0    IT Tech      NaN  12-11-2020
8       Kuppusamy  28.0        Ops      NaN  21-05-2021
9           Ajesh  28.0    Support      NaN  30-07-2024
10           Diya  31.0    IT Tech  63000.0  12-11-2020
11        Mathiew   NaN    Support  58000.0  15-01-2025
12  Jagadheeswari  28.0    IT Tech      NaN         NaN
13           Mani  28.0        Ops      NaN  21-05-2021

In [57]:
employee_details.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
dtype: bool

In [58]:
employee_details.drop_duplicates(inplace = True)

In [59]:
employee_details

             Name   Age Department   Salary   Join_Date
0          Rajesh  29.0        Ops  60000.0  21-05-2023
1           Nasir  31.0    IT Tech  62000.0  12-11-2020
2         Mathiew   NaN    Support  58000.0  15-01-2025
3         Gilbert  29.0        Ops  60000.0  21-05-2021
4           Kevin  28.0    Support  61000.0  30-07-2024
5           Navin  35.0    Support  72000.0  19-08-2023
6             NaN  40.0    IT Tech  64000.0  10-09-2022
7          Roshan  31.0    IT Tech      NaN  12-11-2020
8       Kuppusamy  28.0        Ops      NaN  21-05-2021
9           Ajesh  28.0    Support      NaN  30-07-2024
10           Diya  31.0    IT Tech  63000.0  12-11-2020
12  Jagadheeswari  28.0    IT Tech      NaN         NaN
13           Mani  28.0        Ops      NaN  21-05-2021

### Step 2: Identify Null Entries

In [60]:
employee_details.isnull().sum()

Name          1
Age           1
Department    0
Salary        5
Join_Date     1
dtype: int64

### Step 3: Go for best Imputation 
- Imputation means fill some values in missing areas

In [61]:
employee_details["Department"].unique()

array(['Ops', 'IT Tech', 'Support'], dtype=object)

In [62]:
employee_details[employee_details["Department"] == "IT Tech"]

             Name   Age Department   Salary   Join_Date
1           Nasir  31.0    IT Tech  62000.0  12-11-2020
6             NaN  40.0    IT Tech  64000.0  10-09-2022
7          Roshan  31.0    IT Tech      NaN  12-11-2020
10           Diya  31.0    IT Tech  63000.0  12-11-2020
12  Jagadheeswari  28.0    IT Tech      NaN         NaN

In [63]:
employee_details[employee_details["Department"] == "Ops"]

         Name   Age Department   Salary   Join_Date
0      Rajesh  29.0        Ops  60000.0  21-05-2023
3     Gilbert  29.0        Ops  60000.0  21-05-2021
8   Kuppusamy  28.0        Ops      NaN  21-05-2021
13       Mani  28.0        Ops      NaN  21-05-2021

In [64]:
employee_details[employee_details["Department"] == "Support"]

      Name   Age Department   Salary   Join_Date
2  Mathiew   NaN    Support  58000.0  15-01-2025
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
9    Ajesh  28.0    Support      NaN  30-07-2024

In [65]:
(employee_details["Department"] == "Support") & (employee_details["Salary"].isnull())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
12    False
13    False
dtype: bool

In [66]:
employee_details[(employee_details["Department"] == "Support") & (employee_details["Salary"].isnull())]

    Name   Age Department  Salary   Join_Date
9  Ajesh  28.0    Support     NaN  30-07-2024

## Data Analytics Task
1. Impute The relevant values in the Salary Column wherever it is NaN, based on Department Filtering.
2. Impute Mathiew's Age as 27.

In [76]:
employee_details.loc[(employee_details["Department"] == "Support") & (employee_details["Salary"].isnull()),"Salary"] = 70000.0

In [75]:
employee_details.loc[(employee_details["Department"] == "Support") & (employee_details["Age"].isnull()),"Age"] = 27.0

In [77]:
employee_details[employee_details["Department"] == "Support"]

      Name   Age Department   Salary   Join_Date
2  Mathiew  27.0    Support  58000.0  15-01-2025
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
9    Ajesh  28.0    Support    70000  30-07-2024