## 1. Write a program to take a name and age from the user and print a greeting message.

In [6]:
name = input("Enter Your Name:")
age = int(input("Enter Your Age:"))
print(f"Hurray you're {age} now...{name}!")

Enter Your Name: Aakash
Enter Your Age: 23

Hurray you're 23 now...Aakash!

## 2. Create a list of numbers and print only even numbers using a for loop.

In [12]:
numbers = [1,13,2,4,5,62,74,24]
for num in numbers:
    if num % 2 == 0:
        print(num)

2
4
62
74
24

In [22]:
numerics = range(0,40)
even_numbers = []
for i in numerics:
    if i%2 == 0:
        even_numbers.append(i)
print(even_numbers)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]

## 3. Write a program that handles division by zero using try-except.

In [24]:
try:
    numerator = int(input("Enter numerator: "))
    denominator = int(input("Enter denominator: "))

    result = numerator / denominator
    print("Result:", result)

except ZeroDivisionError:
    print("Error: Cannot divide by zero!")

Enter numerator:  1
Enter denominator:  0

Error: Cannot divide by zero!

## 4. Given a string, count how many vowels it has.

In [26]:
name = input("Enter Your Name:")
vowels_count = 0
for i in name.lower():
    if i in "a,e,i,o,u":
        vowels_count += 1
print(f"Number of vowels:{vowels_count}")

Enter Your Name: AEIOU

Number of vowels:5

## 5. Reverse a list without using built-in functions.

In [28]:
original_list = [1,2,3,4,5,6,7,8,9,10]
reversed_list = []

i = len(original_list) - 1

while i>=0:
    reversed_list.append(original_list[i])
    i-=1

print(reversed_list)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

## 6. Create a dictionary with at least 5 key-value pairs and print them.

In [29]:
new_dictionary = {
    "Space":["Astronaut","Sattelite","Planets","Galaxy"],
    "Airplane":["Pilot","Passengers","Autopilot","AirHostess"],
    "Kitchen":["Cook","Utensils","Vegetables","Meat"],
    "Zoo":["Wild Animals","Birds","Fishes","Domestic Animals"],
}

In [30]:
new_dictionary

{'Space': ['Astronaut', 'Sattelite', 'Planets', 'Galaxy'],
 'Airplane': ['Pilot', 'Passengers', 'Autopilot', 'AirHostess'],
 'Kitchen': ['Cook', 'Utensils', 'Vegetables', 'Meat'],
 'Zoo': ['Wild Animals', 'Birds', 'Fishes', 'Domestic Animals']}

## 7. Write a Pandas code to read a CSV and print the top 5 rows.

In [10]:
import pandas as pd
details_MNC = pd.read_csv("pandas_realistic_dataset.csv")
details_MNC.head()

,id,name,age,salary,city,department,experience_years,rating,joining_year,is_manager
0,1.0,Karthik Kumar,56.0,81476.0,Bangalore,IT,14.0,2.65,2014.0,NaN
1,2.0,Manoj Iyer,46.0,64811.0,NaN,HR,3.0,3.78,2023.0,NaN
2,3.0,Nikhil Reddy,32.0,56208.0,Hyderabad,HR,10.0,1.01,2022.0,True
3,NaN,Karthik Patel,25.0,40150.0,Hyderabad,Marketing,18.0,3.48,2010.0,NaN
4,NaN,NaN,38.0,NaN,NaN,NaN,14.0,2.42,2019.0,False

## 8. Create a DataFrame from a Python dictionary.

In [21]:
pd.DataFrame({
    "Space":["Astronaut","Sattelite","Planets","Galaxy"],
    "Airplane":["Pilot","Passengers","Autopilot","AirHostess"],
    "Kitchen":["Cook","Utensils","Vegetables","Meat"],
    "Zoo":["Wild Animals","Birds","Fishes","Domestic Animals"],
})

       Space    Airplane     Kitchen               Zoo
0  Astronaut       Pilot        Cook      Wild Animals
1  Sattelite  Passengers    Utensils             Birds
2    Planets   Autopilot  Vegetables            Fishes
3     Galaxy  AirHostess        Meat  Domestic Animals

In [17]:
random_files = {
    "Space":["Astronaut","Sattelite","Planets","Galaxy"],
    "Airplane":["Pilot","Passengers","Autopilot","AirHostess"],
    "Kitchen":["Cook","Utensils","Vegetables","Meat"],
    "Zoo":["Wild Animals","Birds","Fishes","Domestic Animals"],
}
pd.DataFrame(random_files).to_csv("random_files.csv",index = False)

## 9. Replace all missing values in a DataFrame with the column's mean.

In [25]:
import pandas as pd
MNC_details = pd.read_csv("pandas_realistic_dataset.csv")

In [26]:
MNC_details["salary"].mean()

np.float64(67821.21588594705)

In [31]:
MNC_details["salary"] = MNC_details["salary"].fillna(MNC_details["salary"].mean())

In [36]:
MNC_details

,id,name,age,salary,city,department,experience_years,rating,joining_year,is_manager
0,1.0,Karthik Kumar,56.0,81476.000000,Bangalore,IT,14.0,2.65,2014.0,NaN
1,2.0,Manoj Iyer,46.0,64811.000000,NaN,HR,3.0,3.78,2023.0,NaN
2,3.0,Nikhil Reddy,32.0,56208.000000,Hyderabad,HR,10.0,1.01,2022.0,True
3,NaN,Karthik Patel,25.0,40150.000000,Hyderabad,Marketing,18.0,3.48,2010.0,NaN
4,NaN,NaN,38.0,67821.215886,NaN,NaN,14.0,2.42,2019.0,False
...,...,...,...,...,...,...,...,...,...,...
545,330.0,NaN,41.0,101818.000000,Hyderabad,Marketing,8.0,3.40,2019.0,True
546,296.0,Anjali Singh,51.0,67821.215886,Chennai,Finance,14.0,3.91,2022.0,True
547,417.0,Anjali Singh,31.0,97149.000000,Chennai,IT,13.0,2.54,2005.0,NaN
548,407.0,Rahul Verma,22.0,37260.000000,Delhi,Marketing,7.0,4.82,2017.0,False
549,103.0,Vikram Gupta,29.0,67821.215886,Chennai,Marketing,13.0,3.24,2008.0,False

## 10. Filter rows in a DataFrame where the "Age" column is greater than 30.

In [43]:
MNC_details[MNC_details["age"] > 30]

,id,name,age,salary,city,department,experience_years,rating,joining_year,is_manager
0,1.0,Karthik Kumar,56.0,81476.000000,Bangalore,IT,14.0,2.65,2014.0,NaN
1,2.0,Manoj Iyer,46.0,64811.000000,NaN,HR,3.0,3.78,2023.0,NaN
2,3.0,Nikhil Reddy,32.0,56208.000000,Hyderabad,HR,10.0,1.01,2022.0,True
4,NaN,NaN,38.0,67821.215886,NaN,NaN,14.0,2.42,2019.0,False
5,6.0,Priya Kumar,56.0,63286.000000,Delhi,Sales,3.0,4.18,2014.0,False
...,...,...,...,...,...,...,...,...,...,...
541,431.0,Vikram Iyer,54.0,99579.000000,Chennai,IT,6.0,1.04,2013.0,False
544,331.0,Divya Reddy,49.0,43624.000000,Bangalore,Marketing,0.0,1.46,2014.0,True
545,330.0,NaN,41.0,101818.000000,Hyderabad,Marketing,8.0,3.40,2019.0,True
546,296.0,Anjali Singh,51.0,67821.215886,Chennai,Finance,14.0,3.91,2022.0,True
547,417.0,Anjali Singh,31.0,97149.000000,Chennai,IT,13.0,2.54,2005.0,NaN