# Task - 1

## List and functions

In [40]:
Stationary_Store = ["Pencil","Pen","Eraser","NoteBook","WaterColor"]
Stationary_Store

['Pencil', 'Pen', 'Eraser', 'NoteBook', 'WaterColor']

In [41]:
type(Stationary_Store)

list

In [42]:
Stationary_Store[0] = 12
Stationary_Store

[12, 'Pen', 'Eraser', 'NoteBook', 'WaterColor']

In [43]:
Stationary_Store.append("Pencil")
Stationary_Store

[12, 'Pen', 'Eraser', 'NoteBook', 'WaterColor', 'Pencil']

In [44]:
Stationary_Store = ["Pencil","Pen","Eraser","NoteBook","WaterColor"]
Stationary_Store_2 = Stationary_Store.copy()
Stationary_Store_2

['Pencil', 'Pen', 'Eraser', 'NoteBook', 'WaterColor']

In [47]:
Stationary_Store_3 = ["Stapler","Geometry Box"]
Stationary_Store_3.extend(Stationary_Store_2)
Stationary_Store_3

['Stapler',
 'Geometry Box',
 'Pencil',
 'Pen',
 'Eraser',
 'NoteBook',
 'WaterColor']

In [49]:
Stationary_Store_3.insert(1,"Marker")
Stationary_Store_3

['Stapler',
 'Marker',
 'Geometry Box',
 'Pencil',
 'Pen',
 'Eraser',
 'NoteBook',
 'WaterColor']

In [50]:
Stationary_Store_3.remove("Stapler")
Stationary_Store_3

['Marker', 'Geometry Box', 'Pencil', 'Pen', 'Eraser', 'NoteBook', 'WaterColor']

In [51]:
Stationary_Store_4 = ["Exam pad","Pouch","Pencil Box"]
Stationary_Store_4.pop()
Stationary_Store_4

['Exam pad', 'Pouch']

In [52]:
Stationary_Store_5 = ["Exam pad","Pouch","Pencil Box","Sketch Pen"]
Stationary_Store_5.reverse()
Stationary_Store_5

['Sketch Pen', 'Pencil Box', 'Pouch', 'Exam pad']

In [53]:
Stationary_Store_5 = ["Exam pad","Pouch","Pencil Box","Sketch Pen"]
print(Stationary_Store_5.index("Pouch"))

1

In [54]:
Stationary_Store_5 = ["Exam pad","Pouch","Pencil Box","Sketch Pen"]
Stationary_Store_5.reverse()
Stationary_Store_5

['Sketch Pen', 'Pencil Box', 'Pouch', 'Exam pad']

In [55]:
Stationary_Store_6 = ["Sketch Pen","Exam pad","Sketch Pen","Pouch","Pencil Box","Sketch Pen"]
print(Stationary_Store_6.count("Sketch Pen"))

3

In [56]:
Commercials = ["Office","School","Collage","Biology","Accounts"]
Commercials .sort()
Commercials

['Accounts', 'Biology', 'Collage', 'Office', 'School']

In [57]:
numbers = [5, 2, 9, 1]
numbers.sort()
numbers

[1, 2, 5, 9]

## Sets and Functions

In [71]:
subjects = {"Botany","Zoology","Physics"}
subjects.add("Chemistry") # Adds one element to the set.
subjects

{'Botany', 'Chemistry', 'Physics', 'Zoology'}

In [72]:
subjects.update(["Tamil","English","Maths"]) # Adds multiple elements.
subjects

{'Botany', 'Chemistry', 'English', 'Maths', 'Physics', 'Tamil', 'Zoology'}

In [73]:
subjects.remove("Maths")
subjects

{'Botany', 'Chemistry', 'English', 'Physics', 'Tamil', 'Zoology'}

In [74]:
subjects_1 = {"Botany","Physics"}
subjects_1.discard("Zoology") # Removes element without error if not present.
subjects_1

{'Botany', 'Physics'}

In [78]:
subjects_3 = {"Botany","Zoology","Physics"}
subjects_3.pop()
subjects_3

{'Botany', 'Zoology'}

In [8]:
subjects_4 = {"Botany","Zoology","Physics"}
subjects_5 = subjects_4.copy()
subjects_5

{'Botany', 'Physics', 'Zoology'}

In [10]:
A = {1,2,3,4}
B = {5,6,7,8}

A.union(B)

{1, 2, 3, 4, 5, 6, 7, 8}

In [11]:
A = {1,2,3,4,5}
B = {4,5,6,7,8}

A.intersection(B)

{4, 5}

In [14]:
A = {1,2,3,4}
B = {3,4,5,6}

A.difference(B)

{1, 2}

In [15]:
A = {1,2,3,4}
B = {3,4,5,6}

A.symmetric_difference(B)

{1, 2, 5, 6}

In [17]:
A = {1,2}
B = {1,2,3,4}

print(A.issubset(B))

True

In [18]:
A = {1,2,3,4}
B = {3,4,5,6}

A.issubset(B)

False

In [19]:
A = {1,2,3,4}
B = {3,4,5,6}

A.issuperset(B)

False

In [21]:
A = {1,2,3,4}
B = {1,2}

print(A.issuperset(B))

True

In [22]:
A = {1,2,3,4}
B = {3,4,5,6}

A.isdisjoint(B)

False

In [23]:
A = {1,2}
B = {3,4}

A.isdisjoint(B)

True

## Tuples and Functions

In [28]:
numbers = (10, 20, 30, 20, 40)

numbers.count(20)

2

In [30]:
numbers.index(40)

3

In [32]:
max(numbers)

40

In [34]:
min(numbers)

10

In [35]:
sum(numbers)

100

In [38]:
numbers = (5, 2, 8, 1)

print(sorted(numbers)) # Note: Result is list, not tuple.

[1, 2, 5, 8]

## Dictionary and functions

In [93]:
student = {"Name": "Aakash", "Age": 23, "Marks": 85}
student.keys()

dict_keys(['Name', 'Age', 'Marks'])

In [94]:
student.values()

dict_values(['Aakash', 23, 85])

In [95]:
student.items()

dict_items([('Name', 'Aakash'), ('Age', 23), ('Marks', 85)])

In [99]:
student.get("Name")

'Aakash'

In [100]:
student.update({"Marks": 98})
student

{'Name': 'Aakash', 'Age': 23, 'Marks': 98}

In [101]:
student.pop("Age") #Removes a key
student

{'Name': 'Aakash', 'Marks': 98}

In [102]:
student.popitem() # Removes last inserted item.
student

{'Name': 'Aakash'}

In [103]:
student.clear()
student

{}

In [104]:
student_2 = {"Name": "Aakash", "Age": 23, "Marks": 85}
new_student = student_2.copy()
new_student

{'Name': 'Aakash', 'Age': 23, 'Marks': 85}

In [105]:
student_3 = {"Name":"Aakash"}
student_3.setdefault("Roll no",2) # Gets value if key exists, otherwise adds new key.
student_3

{'Name': 'Aakash', 'Roll no': 2}

In [106]:
keys = ["Name","Age","Marks"]
new_dictonary = dict.fromkeys(keys, 0) # Creates dictionary with given keys.
new_dictonary

{'Name': 0, 'Age': 0, 'Marks': 0}

# Task 2

## Data Frames using Dictionaries

In [2]:
import pandas as pd

In [6]:
student_data = {
    "Name": ["Aakash", "Santhu", "Regwin", "Vignesh"],
    "Age": [23, 21, 24, 22],
    "Marks": [85, 90, 88, 92]
}

pd.DataFrame(student_data)

      Name  Age  Marks
0   Aakash   23     85
1   Santhu   21     90
2   Regwin   24     88
3  Vignesh   22     92

In [7]:
employee_data = {
    "Employee": ["John", "David", "Sara"],
    "Salary": [50000, 60000, 55000],
    "Department": ["IT", "HR", "Finance"]
}

pd.DataFrame(employee_data)

  Employee  Salary Department
0     John   50000         IT
1    David   60000         HR
2     Sara   55000    Finance

In [110]:
product_data = {
    "Product": ["Laptop", "Phone", "Tablet"],
    "Price": [70000, 30000, 25000],
    "Stock": [10, 20, 15]
}

pd.DataFrame(product_data)

  Product  Price  Stock
0  Laptop  70000     10
1   Phone  30000     20
2  Tablet  25000     15

In [4]:
product_data = {
    "Product": ["Laptop", "Phone", "Tablet"],
    "Price": [70000, 30000, 25000],
    "Stock": [10, 20, 15]
}

pd.DataFrame(product_data,index = 0)

TypeError: Index(...) must be called with a collection of some kind, 0 was passed