# Data Structures in Python
* To collect multiple data in a structure

## Types of Data Structures

### 1. List
* Duplicate Values
* One Dimensional
* Hetrogenous(can contain int,float,strings)
* Indexing & Sclicing is possible
* Mutubale(Can change values inside List)

In [1]:
empty_cart = []

In [2]:
empty_cart

[]

In [3]:
type(empty_cart)

list

In [6]:
items_to_buy = ["Apple","Orange","Pomegranate","Apple",6,98,90.8]
items_to_buy

['Apple', 'Orange', 'Pomegranate', 'Apple', 6, 98, 90.8]

In [5]:
type(items_to_buy)

list

### Note:
#### During Indexing:
* Always positive indexing starts from 0 (starts from left to right).           
* Always Negative indexing starts from -1 (starts from right to left).

#### During Sclicing:
* for positive indexing:
    it starts from 0 and ending should be the next index number to get exact Value.
* for negative indexing:
    it Starts from -1 (Moves right → left)

In [9]:
items_to_buy[0]

'Apple'

In [10]:
items_to_buy[-3]

6

In [13]:
items_to_buy[2:6]

['Pomegranate', 'Apple', 6, 98]

In [16]:
items_to_buy[-6:-1]

['Orange', 'Pomegranate', 'Apple', 6, 98]

In [19]:
items_to_buy[2] = "StarFuit"
items_to_buy

['Apple', 'Orange', 'StarFuit', 'Apple', 6, 98, 90.8]

### 2. Sets
* it Doesn't allow Duplicate Values
* One Dimensional
* Hetrogenous(can contain int,float,strings)
* Indexing & Sclicing is not possible
* Mutubale(Can change values inside Sets)

In [24]:
empty_set = set()
type(empty_set)

set

In [27]:
items_to_buy_2 = {"Apple","Orange","Pomegranate","Apple",6,98,90.8}
items_to_buy_2

{6, 90.8, 98, 'Apple', 'Orange', 'Pomegranate'}

In [28]:
items_to_buy_2.add("Potato")

In [29]:
items_to_buy_2

{6, 90.8, 98, 'Apple', 'Orange', 'Pomegranate', 'Potato'}

In [30]:
items_to_buy_2.discard("Apple")

In [31]:
items_to_buy_2

{6, 90.8, 98, 'Orange', 'Pomegranate', 'Potato'}

### 3. Tuples
* it allow Duplicate Values
* One Dimensional
* Hetrogenous(can contain int,float,strings)
* Indexing & Sclicing is possible
* Immutubale(Cannot change values inside Tuple)

In [34]:
empty_tuple = ()
type(empty_tuple)

tuple

In [35]:
items_to_buy_3 = ("Apple","Orange","Pomegranate","Apple",6,98,90.8)
items_to_buy_3

('Apple', 'Orange', 'Pomegranate', 'Apple', 6, 98, 90.8)

In [36]:
items_to_buy_3[0:3]

('Apple', 'Orange', 'Pomegranate')

In [38]:
items_to_buy_3.count("Apple")

2

In [39]:
items_to_buy_3.index("Apple")

0

### 4. Dictionary
It is a key value pair
* Don't create duplicate keys, it allow Duplicate Values but duplicate value is updated to original value
* Two Dimensional
* Hetrogenous(can contain int,float,strings)
* Indexing & Sclicing is not possible
* Mutable(Can change values inside Dictionary)

In [42]:
empty_dictionary = {}
type(empty_dictionary)

dict

In [43]:
student_marks = {"Maths":76,
                "English":93,
                "Science":98}

In [44]:
student_marks

{'Maths': 76, 'English': 93, 'Science': 98}

In [48]:
items_to_buy_4 = {"Apple":5,"Orange":3,"Pomegranate":1,"Apple":4} # Refer the 1st point in Dictionary
items_to_buy_4

{'Apple': 4, 'Orange': 3, 'Pomegranate': 1}

In [51]:
items_to_buy_4.clear()
items_to_buy_4

{}

In [61]:
items_to_buy_5 = {"Apple":5,"Orange":3,"Pomegranate":1}
items_to_buy_5.keys()

dict_keys(['Apple', 'Orange', 'Pomegranate'])

In [62]:
items_to_buy_5.values()

dict_values([5, 3, 1])

## Pandas implementation

In [2]:
import pandas as pd

In [3]:
public_exam_marks = {"Subjects":["Tamil","English","Maths","Science","Social"],"Student1":[89,93,76,98,98],"Student2":[98,93,48,100,97]}
public_exam_marks

{'Subjects': ['Tamil', 'English', 'Maths', 'Science', 'Social'],
 'Student1': [89, 93, 76, 98, 98],
 'Student2': [98, 93, 48, 100, 97]}

In [4]:
pd.DataFrame(data = public_exam_marks)

  Subjects  Student1  Student2
0    Tamil        89        98
1  English        93        93
2    Maths        76        48
3  Science        98       100
4   Social        98        97

In [5]:
public_exam_marks_2 = {"Subjects":["Social","Science","Maths"],"Marks":[89,76,48],"Grade":["A","B","C"]}
public_exam_marks_2

{'Subjects': ['Social', 'Science', 'Maths'],
 'Marks': [89, 76, 48],
 'Grade': ['A', 'B', 'C']}

In [6]:
pd.DataFrame(data = public_exam_marks_2)

  Subjects  Marks Grade
0   Social     89     A
1  Science     76     B
2    Maths     48     C