In [1]:
import pandas as pd

In [2]:
sales_data_2017 = pd.read_csv("Sales Transactions-2017.csv")
sales_data_2018 = pd.read_csv("Sales Transactions-2018.csv")
sales_data_2019 = pd.read_csv("Sales Transactions-2019.csv")

In [3]:
sales_full_data = pd.concat(objs = [sales_data_2017,sales_data_2018,sales_data_2019])
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [64]:
sales_dataset = pd.read_csv("new.csv")
sales_dataset

,Unnamed: 0,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
111201,19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
111202,19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111203,19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111204,19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
111205,19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [65]:
sales_dataset.isnull().sum()

Unnamed: 0             0
Date               12591
Voucher            12557
Party                 40
Product            12591
Qty                12557
Rate               12558
Gross              12558
Disc              105609
Voucher Amount     83646
dtype: int64

In [66]:
sales_dataset.dtypes

Unnamed: 0         int64
Date              object
Voucher           object
Party             object
Product           object
Qty               object
Rate              object
Gross             object
Disc              object
Voucher Amount    object
dtype: object

In [67]:
sales_dataset.rename(columns={"Unnamed: 0": "serial.no"}, inplace=True)

In [68]:
sales_dataset

,serial.no,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
111201,19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
111202,19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111203,19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111204,19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
111205,19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [69]:
sales_dataset.drop_duplicates()

,serial.no,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
111201,19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
111202,19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111203,19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111204,19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
111205,19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [70]:
del sales_dataset["serial.no"]

In [71]:
sales_dataset

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
111201,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
111202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111204,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
111205,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [72]:
sales_dataset

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
111201,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
111202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111204,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
111205,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [73]:
sales_dataset.dtypes

Date              object
Voucher           object
Party             object
Product           object
Qty               object
Rate              object
Gross             object
Disc              object
Voucher Amount    object
dtype: object

In [74]:
sales_dataset.describe(include = "all")

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
count,98615,98649,111166,98615,98649,98648,98648,5597,27560
unique,836,10044,1994,867,546,1109,2548,371,7149
top,,,TP13,,100,,,,
freq,3053,3053,13056,3053,12528,3051,3053,3053,3053

In [75]:
sales_dataset["Date"] = pd.to_datetime(sales_dataset["Date"], errors="coerce")
sales_dataset["Date"] = sales_dataset["Date"].ffill()

In [76]:
sales_dataset

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-01-04,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,2017-01-04,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,2017-01-04,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,2017-01-04,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,2017-01-04,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
111201,2019-10-10,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
111202,2019-10-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111203,2019-10-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111204,2019-10-10,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
111205,2019-10-10,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [77]:
sales_dataset["Date"] = sales_dataset["Date"].dt.strftime("%d/%m/%Y")
sales_dataset

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,04/01/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,04/01/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,04/01/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,04/01/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,04/01/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
111201,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
111202,10/10/2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111203,10/10/2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111204,10/10/2019,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
111205,10/10/2019,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [78]:
sales_dataset["Date"] = pd.to_datetime(sales_dataset["Date"], dayfirst=True)
sales_dataset

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-01-04,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,2017-01-04,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,2017-01-04,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,2017-01-04,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,2017-01-04,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
111201,2019-10-10,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
111202,2019-10-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111203,2019-10-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111204,2019-10-10,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
111205,2019-10-10,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [79]:
sales_dataset["Voucher"] = sales_dataset["Voucher"].str.replace("Sal:","")
sales_dataset

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-01-04,1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,2017-01-04,1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,2017-01-04,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,2017-01-04,2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,2017-01-04,2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
111201,2019-10-10,4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
111202,2019-10-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111203,2019-10-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111204,2019-10-10,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
111205,2019-10-10,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [80]:
sales_dataset["Voucher"] = sales_dataset["Voucher"].ffill()
sales_dataset

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-01-04,1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,2017-01-04,1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,2017-01-04,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,2017-01-04,2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,2017-01-04,2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
111201,2019-10-10,4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
111202,2019-10-10,4935,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111203,2019-10-10,4935,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111204,2019-10-10,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
111205,2019-10-10,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [81]:
pd.read_csv("Sales-Transactions-Edited.csv")

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0
...,...,...,...,...,...,...
95557,12/9/2019,4265,TP13,SPOON MED M.W,20,11.0
95558,12/9/2019,4266,K.SRIHARI,SMART BOUL(48),1,1830.0
95559,12/9/2019,4267,SMS,SMARTBOUL GLA(4000),1,1520.0
95560,12/9/2019,4268,ANILFANCY,RR WINEGLASS,100,20.0
95561,12/9/2019,4268,ANILFANCY,RR WATER GLASS,100,20.0

In [82]:
sales_dataset["Voucher"] = pd.to_numeric(sales_dataset["Voucher"], errors="coerce")

In [83]:
sales_dataset["Voucher"] = sales_dataset["Voucher"].astype("Int64")

In [84]:
sales_dataset.dtypes

Date              datetime64[ns]
Voucher                    Int64
Party                     object
Product                   object
Qty                       object
Rate                      object
Gross                     object
Disc                      object
Voucher Amount            object
dtype: object

In [85]:
del sales_dataset["Disc"]

In [86]:
sales_dataset

,Date,Voucher,Party,Product,Qty,Rate,Gross,Voucher Amount
0,2017-01-04,1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00","13,100.00"
1,2017-01-04,1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN
2,2017-01-04,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00","30,990.00"
3,2017-01-04,2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN
4,2017-01-04,2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN
...,...,...,...,...,...,...,...,...
111201,2019-10-10,4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN
111202,2019-10-10,4935,NaN,NaN,NaN,NaN,NaN,NaN
111203,2019-10-10,4935,NaN,NaN,NaN,NaN,NaN,NaN
111204,2019-10-10,<NA>,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","2,189,014.50"
111205,2019-10-10,<NA>,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","52,830,224.40"

In [87]:
del sales_dataset["Gross"]

In [88]:
del sales_dataset["Voucher Amount"]

In [89]:
sales_dataset

,Date,Voucher,Party,Product,Qty,Rate
0,2017-01-04,1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00"
1,2017-01-04,1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00"
2,2017-01-04,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23
3,2017-01-04,2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00"
4,2017-01-04,2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00"
...,...,...,...,...,...,...
111201,2019-10-10,4935,K.SRIHARI,13*16 WHITE RK,400,16
111202,2019-10-10,4935,NaN,NaN,NaN,NaN
111203,2019-10-10,4935,NaN,NaN,NaN,NaN
111204,2019-10-10,<NA>,NaN,NaN,"99,284.90","175,381.65"
111205,2019-10-10,<NA>,NaN,NaN,"2,710,193.00","5,519,888.40"

In [90]:
sales_dataset["Rate"] = sales_dataset["Rate"].str.replace(",","")

In [91]:
sales_dataset

,Date,Voucher,Party,Product,Qty,Rate
0,2017-01-04,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.00
1,2017-01-04,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.00
2,2017-01-04,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23
3,2017-01-04,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.00
4,2017-01-04,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.00
...,...,...,...,...,...,...
111201,2019-10-10,4935,K.SRIHARI,13*16 WHITE RK,400,16
111202,2019-10-10,4935,NaN,NaN,NaN,NaN
111203,2019-10-10,4935,NaN,NaN,NaN,NaN
111204,2019-10-10,<NA>,NaN,NaN,"99,284.90",175381.65
111205,2019-10-10,<NA>,NaN,NaN,"2,710,193.00",5519888.40

In [92]:
sales_dataset["Rate"] = pd.to_numeric(sales_dataset["Rate"], errors="coerce")

In [93]:
sales_dataset["Rate"].astype(float)

0            1690.00
1            1620.00
2              23.00
3            1620.00
4            1690.00
             ...
111201         16.00
111202           NaN
111203           NaN
111204     175381.65
111205    5519888.40
Name: Rate, Length: 111206, dtype: float64

In [94]:
sales_dataset.dtypes

Date       datetime64[ns]
Voucher             Int64
Party              object
Product            object
Qty                object
Rate              float64
dtype: object

In [95]:
sales_dataset["Qty"] = pd.to_numeric(sales_dataset["Qty"],errors = "coerce")

In [96]:
sales_dataset

,Date,Voucher,Party,Product,Qty,Rate
0,2017-01-04,1,SOLANKI PLASTICS,DONA-VAI-9100,2.0,1690.00
1,2017-01-04,1,SOLANKI PLASTICS,LITE FOAM(1200),6.0,1620.00
2,2017-01-04,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23.00
3,2017-01-04,2,SARNESWARA TRADERS,LITE FOAM(1200),6.0,1620.00
4,2017-01-04,2,SARNESWARA TRADERS,DONA-VAI-9100,5.0,1690.00
...,...,...,...,...,...,...
111201,2019-10-10,4935,K.SRIHARI,13*16 WHITE RK,400.0,16.00
111202,2019-10-10,4935,NaN,NaN,NaN,NaN
111203,2019-10-10,4935,NaN,NaN,NaN,NaN
111204,2019-10-10,<NA>,NaN,NaN,NaN,175381.65
111205,2019-10-10,<NA>,NaN,NaN,NaN,5519888.40

In [97]:
pd.read_csv("Sales-Transactions-Edited.csv").dtypes

Date        object
Voucher      int64
Party       object
Product     object
Qty          int64
Rate       float64
dtype: object

In [98]:
sales_dataset["Qty"] = sales_dataset["Qty"].ffill()

In [99]:
sales_dataset

,Date,Voucher,Party,Product,Qty,Rate
0,2017-01-04,1,SOLANKI PLASTICS,DONA-VAI-9100,2.0,1690.00
1,2017-01-04,1,SOLANKI PLASTICS,LITE FOAM(1200),6.0,1620.00
2,2017-01-04,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23.00
3,2017-01-04,2,SARNESWARA TRADERS,LITE FOAM(1200),6.0,1620.00
4,2017-01-04,2,SARNESWARA TRADERS,DONA-VAI-9100,5.0,1690.00
...,...,...,...,...,...,...
111201,2019-10-10,4935,K.SRIHARI,13*16 WHITE RK,400.0,16.00
111202,2019-10-10,4935,NaN,NaN,400.0,NaN
111203,2019-10-10,4935,NaN,NaN,400.0,NaN
111204,2019-10-10,<NA>,NaN,NaN,400.0,175381.65
111205,2019-10-10,<NA>,NaN,NaN,400.0,5519888.40

In [100]:
sales_dataset["Rate"] = sales_dataset["Rate"].ffill()
sales_dataset

,Date,Voucher,Party,Product,Qty,Rate
0,2017-01-04,1,SOLANKI PLASTICS,DONA-VAI-9100,2.0,1690.00
1,2017-01-04,1,SOLANKI PLASTICS,LITE FOAM(1200),6.0,1620.00
2,2017-01-04,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23.00
3,2017-01-04,2,SARNESWARA TRADERS,LITE FOAM(1200),6.0,1620.00
4,2017-01-04,2,SARNESWARA TRADERS,DONA-VAI-9100,5.0,1690.00
...,...,...,...,...,...,...
111201,2019-10-10,4935,K.SRIHARI,13*16 WHITE RK,400.0,16.00
111202,2019-10-10,4935,NaN,NaN,400.0,16.00
111203,2019-10-10,4935,NaN,NaN,400.0,16.00
111204,2019-10-10,<NA>,NaN,NaN,400.0,175381.65
111205,2019-10-10,<NA>,NaN,NaN,400.0,5519888.40

In [101]:
sales_dataset.dtypes

Date       datetime64[ns]
Voucher             Int64
Party              object
Product            object
Qty               float64
Rate              float64
dtype: object

In [102]:
sales_dataset["Qty"] = sales_dataset["Qty"].astype(int)
sales_dataset

,Date,Voucher,Party,Product,Qty,Rate
0,2017-01-04,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.00
1,2017-01-04,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.00
2,2017-01-04,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.00
3,2017-01-04,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.00
4,2017-01-04,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.00
...,...,...,...,...,...,...
111201,2019-10-10,4935,K.SRIHARI,13*16 WHITE RK,400,16.00
111202,2019-10-10,4935,NaN,NaN,400,16.00
111203,2019-10-10,4935,NaN,NaN,400,16.00
111204,2019-10-10,<NA>,NaN,NaN,400,175381.65
111205,2019-10-10,<NA>,NaN,NaN,400,5519888.40

In [103]:
sales_dataset.dtypes

Date       datetime64[ns]
Voucher             Int64
Party              object
Product            object
Qty                 int64
Rate              float64
dtype: object

In [104]:
sales_dataset = sales_dataset.drop_duplicates().dropna()
sales_dataset

,Date,Voucher,Party,Product,Qty,Rate
0,2017-01-04,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0
1,2017-01-04,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0
2,2017-01-04,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0
3,2017-01-04,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0
4,2017-01-04,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0
...,...,...,...,...,...,...
111197,2019-10-10,4935,K.SRIHARI,16*20(100-W),140,26.0
111198,2019-10-10,4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4
111199,2019-10-10,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16.0
111200,2019-10-10,4935,K.SRIHARI,10*12 RK,800,8.5
111201,2019-10-10,4935,K.SRIHARI,13*16 WHITE RK,400,16.0

In [105]:
sales_dataset.dtypes

Date       datetime64[ns]
Voucher             Int64
Party              object
Product            object
Qty                 int64
Rate              float64
dtype: object

In [109]:
sales_dataset.to_csv("Cleaned_sales_dataset.csv")