In [1]:
import pandas as pd

In [5]:
ordered_items = pd.read_csv("orders.csv")
ordered_items

   order_id  customer_id  product  amount
0         1          101   Laptop   70000
1         2          102    Phone   30000
2         3          101   Tablet   25000
3         4          105  Monitor   15000

In [6]:
customers_details = pd.read_csv("customers.csv")
customers_details

   customer_id    name       city
0          101  Aakash    Chennai
1          102   Rahul     Mumbai
2          103   Priya      Delhi
3          104   Sneha  Bangalore

In [9]:
pd.merge(customers_details,ordered_items)

   customer_id    name     city  order_id product  amount
0          101  Aakash  Chennai         1  Laptop   70000
1          101  Aakash  Chennai         3  Tablet   25000
2          102   Rahul   Mumbai         2   Phone   30000

In [10]:
pd.merge(customers_details,ordered_items, on='customer_id', how='inner')

   customer_id    name     city  order_id product  amount
0          101  Aakash  Chennai         1  Laptop   70000
1          101  Aakash  Chennai         3  Tablet   25000
2          102   Rahul   Mumbai         2   Phone   30000

In [11]:
pd.merge(customers_details,ordered_items, on='customer_id', how='left')

   customer_id    name       city  order_id product   amount
0          101  Aakash    Chennai       1.0  Laptop  70000.0
1          101  Aakash    Chennai       3.0  Tablet  25000.0
2          102   Rahul     Mumbai       2.0   Phone  30000.0
3          103   Priya      Delhi       NaN     NaN      NaN
4          104   Sneha  Bangalore       NaN     NaN      NaN

In [12]:
pd.merge(customers_details,ordered_items, on='customer_id', how='right')

   customer_id    name     city  order_id  product  amount
0          101  Aakash  Chennai         1   Laptop   70000
1          102   Rahul   Mumbai         2    Phone   30000
2          101  Aakash  Chennai         3   Tablet   25000
3          105     NaN      NaN         4  Monitor   15000

In [13]:
pd.merge(customers_details,ordered_items, on='customer_id', how='outer')

   customer_id    name       city  order_id  product   amount
0          101  Aakash    Chennai       1.0   Laptop  70000.0
1          101  Aakash    Chennai       3.0   Tablet  25000.0
2          102   Rahul     Mumbai       2.0    Phone  30000.0
3          103   Priya      Delhi       NaN      NaN      NaN
4          104   Sneha  Bangalore       NaN      NaN      NaN
5          105     NaN        NaN       4.0  Monitor  15000.0

In [15]:
pd.merge(customers_details,ordered_items, how='cross')

    customer_id_x    name       city  order_id  customer_id_y  product  amount
0             101  Aakash    Chennai         1            101   Laptop   70000
1             101  Aakash    Chennai         2            102    Phone   30000
2             101  Aakash    Chennai         3            101   Tablet   25000
3             101  Aakash    Chennai         4            105  Monitor   15000
4             102   Rahul     Mumbai         1            101   Laptop   70000
5             102   Rahul     Mumbai         2            102    Phone   30000
6             102   Rahul     Mumbai         3            101   Tablet   25000
7             102   Rahul     Mumbai         4            105  Monitor   15000
8             103   Priya      Delhi         1            101   Laptop   70000
9             103   Priya      Delhi         2            102    Phone   30000
10            103   Priya      Delhi         3            101   Tablet   25000
11            103   Priya      Delhi         4            105  Monitor   15000
12            104   Sneha  Bangalore         1            101   Laptop   70000
13            104   Sneha  Bangalore         2            102    Phone   30000
14            104   Sneha  Bangalore         3            101   Tablet   25000
15            104   Sneha  Bangalore         4            105  Monitor   15000